### ISSUE TITLE
归一化

### ISSUE THREAD

**Issue by 1qingqing1** [BigRoddy/CMIN-Dataset#1]
请问price数据是如何进行归一化的

**Comment by BigRoddy** [comment]
价格数据的归一化是通过计算其相对于前一个交易日的变化幅度来实现的，具体的计算公式为：
归一化价格 = （当日价格 - 前一日价格）/ 前一日价格

**Comment by 1qingqing1** [comment]
以000001.sz 平安银行为例 : 2018/1/2归一化前的数据为[13.35,13.93 ,13.32 ,13.7 ,13.238302,208159255], 2018/1/3归一化前的数据为[13.73,13.86 ,13.2 ,13.33 ,12.880772,296249838]。2018/1/3归一化后的数据为[-0.027007240052387294, 0.03714207456515203, 0.04696206507450883, -0.0028932713576106544, 0.0069267191517462705, 296249838]。
我使用开盘价（13.73-13.35）/13.35=0.02846并不能和归一化后的数据对应上，使用收盘价（13.33-13.7）/13.7=-0.027007299也不能和归一化后的第一个数据完全对应上，请问我这里计算哪里出问题了呢？

**Comment by BigRoddy** [comment]
您好，可能是之前表述没有特别清楚，中文数据使用的前一日价格统一为前一个交易日的调整后收盘价Adj Close。
第一个数据即label，为调整后收盘价自身的变化幅度；后面的四个数据依次为开盘、最高、最低和收盘价相对于前一个交易日调整后收盘价的变化幅度。
参照上述例子，第一个数据的计算方式为（12.880772-13.238302）/ 13.238302 = -0.027007240052387294；开盘价的归一化数据计算方式为（13.73-13.238302）/ 13.238302 = 0.03714207456515203；分别与归一化后数据的第一个和第二个符合。

**Comment by 1qingqing1** [comment]
懂了，谢谢您的解答。另外还想向您请教一下，vocab.txt是如何处理得到的，这个vocab只包含新闻中出现的词吗？对于英文的vocab，我发现并不是每个单词看成是一个词，比如“2018?”、“battery-...”，对于中文感觉是每一个字当成一个词放到这个vocab文件中，所以中英文处理逻辑不太相同？

**Comment by BigRoddy** [comment]
感谢提醒，此处的vocab.txt是论文中使用GloVe来训练数据集词向量时而划分的，具体的划分方式可以参照[GloVe](https://github.com/stanfordnlp/GloVe)的官方教程。
您也可以使用各种新的nlp技术来对数据集中的文本进行分词编码来实现Word2vec，包括但不限于BPE、Tokenizer等，因此此处的词表并不是确定和唯一的，且与数据集本身没有关系，请根据下游任务来选择相应的分词策略。
